### ISSUE TITLE
Public launch

### ISSUE THREAD

**Issue by Atinux** [nuxt-themes/alpine#77]
- [x] Move to Elements
- [x] Remove Tailwind
- [x] Document design tokens usage: #74 
- [x] Open source it
- [x] Add it to nuxt.new
